name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Resolve missing dependency
        run: go mod download github.com/davecgh/go-spew
      
      - name: Verify dependencies
        run: go mod verify
  
      - name: Build
        run: go build -v ./...
  
      - name: Run go vet
        run: go vet ./...
  
      - name: Install golint
        run: go install golang.org/x/lint/golint@latest
  
      - name: Run golint
        run: golint ./...
  
      - name: Run tests
        run: go test -race -vet=off ./...